#![allow(unsafe_op_in_unsafe_fn)]
//! macOS InputMethodKit FFI backend.
//!
//! This module exposes a C-API for the native Swift implementation of the macOS input method.
//! The Swift codebase links against this library statically and invokes these functions.

use crate::core::{Action, CoreState, handle_key};
use std::ffi::c_void;

/// Callbacks provided by Swift to handle actions generated by the core engine.
#[repr(C)]
pub struct XKeyCallbacks {
    /// Opaque pointer to the Swift context (e.g., the input controller instance)
    pub context: *mut c_void,

    /// Callback to update the preedit text
    /// Args: context, text_utf8_ptr, text_len, caret_pos, visible
    pub update_preedit: extern "C" fn(*mut c_void, *const u8, usize, usize, bool),

    /// Callback to hide the preedit text
    /// Args: context
    pub hide_preedit: extern "C" fn(*mut c_void),

    /// Callback to commit text
    /// Args: context, text_utf8_ptr, text_len
    pub commit: extern "C" fn(*mut c_void, *const u8, usize),
}

/// Creates a new CoreState instance.
/// Returns a raw pointer that must be freed using `xkey_core_destroy`.
#[unsafe(no_mangle)]
pub extern "C" fn xkey_core_create() -> *mut CoreState {
    Box::into_raw(Box::new(CoreState::default()))
}

/// Destroys a CoreState instance.
///
/// # Safety
/// `core` must be a valid pointer returned by `xkey_core_create`, or null.
/// After this call, the pointer is invalid and must not be used.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xkey_core_destroy(core: *mut CoreState) {
    if !core.is_null() {
        let _ = Box::from_raw(core);
    }
}

/// Clears the internal buffer of the CoreState.
///
/// # Safety
/// `core` must be a valid pointer returned by `xkey_core_create`, or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xkey_core_clear_buffer(core: *mut CoreState) {
    if let Some(c) = core.as_mut() {
        c.buffer.clear();
    }
}

/// Helper function to process actions and invoke the appropriate callbacks.
unsafe fn process_actions(actions: Vec<Action>, callbacks: XKeyCallbacks) -> bool {
    let mut consumed = false;

    for action in actions {
        match action {
            Action::UpdatePreedit {
                text,
                caret,
                visible,
            } => {
                (callbacks.update_preedit)(
                    callbacks.context,
                    text.as_ptr(),
                    text.len(),
                    caret,
                    visible,
                );
            }
            Action::HidePreedit => {
                (callbacks.hide_preedit)(callbacks.context);
            }
            Action::Commit(text) => {
                (callbacks.commit)(callbacks.context, text.as_ptr(), text.len());
            }
            Action::Consume => {
                consumed = true;
            }
            Action::PassThrough => {}
        }
    }

    consumed
}

/// Handles a key event and invokes the provided callbacks to perform actions.
/// Returns true if the key was consumed, false if it should be passed through.
///
/// # Safety
/// `core` must be a valid pointer returned by `xkey_core_create`, or null.
/// `callbacks` must contain valid function pointers and a valid context pointer.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xkey_core_handle_key(
    core: *mut CoreState,
    keyval: u32,
    state: u32,
    callbacks: XKeyCallbacks,
) -> bool {
    if let Some(c) = core.as_mut() {
        let actions = handle_key(c, keyval, state);
        process_actions(actions, callbacks)
    } else {
        false
    }
}

/// Commits any pending text in the buffer (used when deactivating).
/// Returns true if text was committed.
///
/// # Safety
/// `core` must be a valid pointer returned by `xkey_core_create`, or null.
/// `callbacks` must contain valid function pointers and a valid context pointer.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xkey_core_flush_buffer(
    core: *mut CoreState,
    callbacks: XKeyCallbacks,
) -> bool {
    if let Some(c) = core.as_mut() {
        if c.buffer.is_empty() {
            return false;
        }
        let text = crate::core::vi_transform(&c.buffer);
        c.buffer.clear();
        let actions = vec![Action::Commit(text), Action::HidePreedit];
        process_actions(actions, callbacks);
        true
    } else {
        false
    }
}
