name: Rust CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-linux:
    name: Check, Format & Clippy (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config
      - name: Rustup show
        run: rustup show
      - name: Cargo fmt
        run: cargo fmt --check
      - name: Cargo clippy
        run: cargo clippy -- -D warnings

  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  check-macos:
    name: Check & Clippy (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup show
        run: rustup show
      - name: Cargo fmt
        run: cargo fmt --check
      - name: Cargo clippy
        run: cargo clippy -- -D warnings

  test-macos:
    name: Test (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  check-windows:
    name: Check & Clippy (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup show
        run: rustup show
      - name: Cargo fmt
        run: cargo fmt --check
      - name: Cargo clippy
        run: cargo clippy -- -D warnings

  test-windows:
    name: Test (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
